CREATE DATABASE IF NOT EXISTS testdb;
USE testdb;

CREATE TABLE IF NOT EXISTS plan_admin (
    plan_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    plan_code VARCHAR(30) NOT NULL UNIQUE,
    plan_name VARCHAR(100) NOT NULL,
    speed VARCHAR(40) NOT NULL,
    data_limit VARCHAR(100) NOT NULL,
    ott_count INT NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    olt_type VARCHAR(30) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
