CREATE DATABASE IF NOT EXISTS testdb;
USE testdb;

DROP TABLE IF EXISTS plan_admin;

CREATE TABLE plan_admin (
    plan_id BIGINT PRIMARY KEY AUTO_INCREMENT,
<<<<<<< HEAD
    plan_code VARCHAR(30) NOT NULL UNIQUE,
=======
>>>>>>> 51191e86410df2cfde3822467b32f20f20c724c4
    plan_name VARCHAR(100) NOT NULL,
    speed VARCHAR(40) NOT NULL,
    data_limit VARCHAR(100) NOT NULL,
    ott_count INT NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    olt_type VARCHAR(30) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
