CREATE DATABASE IF NOT EXISTS testdb;
USE testdb;

DROP TABLE IF EXISTS user;
CREATE TABLE user (
    user_id BIGINT PRIMARY KEY AUTO_INCREMENT,

    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,

    role_id BIGINT NOT NULL,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
DROP TABLE IF EXISTS role;
CREATE TABLE role (
    role_id BIGINT PRIMARY KEY AUTO_INCREMENT,

    role_code VARCHAR(50) NOT NULL UNIQUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO role (role_code) VALUES
('ADMIN'),
('CSR'),
('MAINT');

ALTER TABLE user
ADD CONSTRAINT fk_user_role
FOREIGN KEY (role_id) REFERENCES role(role_id)
ON DELETE RESTRICT
ON UPDATE CASCADE;